### ISSUE TITLE
`pkgs.dzgui` is missing

### ISSUE THREAD

**Issue by arminveres** [lelgenio/dzgui-nix#4]
Hi there, I am unable to activate dzgui using `programs.dzgui.enable = true`, and the only way it worked was by adding this flake as an overlay and then use the `dzgui` package itself.
I am on NixOS unstable.

If you need additional infos, don't hesitate to request them.

**Comment by lelgenio** [comment]
Hi, thanks for opening the issue.

Could you please commit the configuration where you are encountering this problem (to a separate branch in your configuration repo, probably), and share it here?

I'm trying to figure out what could be causing this problem, and made some changes that may or may not fix it for you. If you could check if the problem has been fixed, I'd be grateful. :smiley:

**Comment by arminveres** [comment]
Hey man, thanks, your commit seemed to fix it!
